version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: personal_library_postgres
    restart: always
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_DB: personal_library
    ports:
      - "5433:5432"     # if this is busy, change to "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
