spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/personal_library 
    username: library_user
    password: library_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  google:
    books:
      # put your actual key in an env var, or paste it here for local only
      apiKey: AIzaSyC1kYE2d5EA2SE7nr-wGwNUvX7wbHRgegA

server:
  port: 8080

app:
  jwt:
    secret: "uvEipNNm4/QsSFZkiHrmvybnRmm8krYnxUxGxcz+W9aGk3W4g7P5OVlv+YaCvd3hwvp+OHG0Rlcn8eDb92isXw=="
    issuer: "personal-library"
    accessTokenMinutes: 60
    refreshTokenDays: 7
